name: engauge
version: '10.6'
summary: Interactively convert a bitmap graph or map into numbers.
description: Software tool for extracting numbers from images of graphs and maps.
grade: devel
confinement: strict

parts:
  engauge:
    plugin: qmake
    options: [CONFIG+=log4cpp_null, QT+=printsupport]
    qt-version: qt5
    source: ..
    after: [desktop-qt5]
    
apps:
  engauge:
    plugs: [cups-control]  
    command: desktop-launch ../bin/engauge

